/**
 * Updates branding link and removes blocking CSS classes.
 * @param {HTMLElement} logo 
 */
function update(logo) {
    logo.href = "https://github.com/xFufly/fossnote";
    logo.setAttribute("aria-label", "Aller voir Fossnote");

    const UI = document.querySelector("#div > div.interface_affV.stopwith-footer");
    if (UI) {
        UI.classList.remove("stopwith-footer");
    }
}

let currentDayIndex = 0;

function initDayNavigator() {
    // Pronote can dynamically change IDs (e.g. Instances[6] to Instances[7]). 
    // We must use robust partial matching for the main grid components.
    const grille = document.querySelector('.grille');
    const headerContent = document.querySelector('[id$="_Contenu_TitreHaut"]');
    const gridContent = document.querySelector('[id$="_Contenu_Grille"]');
    
    // We also need the viewports to set dynamic width
    const headerViewport = document.querySelector('[id$="_Zone_TitreHaut"]');
    const gridViewport = document.querySelector('[id$="_Zone_Grille"]');

    if (!grille || !headerContent || !gridContent || !headerViewport || !gridViewport) return;
    if (window.innerWidth > 768) return;

    // Dynamically calculate the width of a single day column generated by Hyperplanning
    const totalDays = document.querySelectorAll('[id$="_Contenu_TitreHaut"] > div').length || 6;
    
    // Custom Coordinate Mapping: Uncompress the grid natively without scaling text!
    let globalScale = window.fossnoteScale || 1;
    let targetDayWidth = window.fossnoteTargetWidth || (window.innerWidth - 40);

    const firstDayEl = document.querySelector('[id$="_titreTranche0"]:not([data-scaled])');
    if (firstDayEl && firstDayEl.style.width) {
        const nativeDayWidth = parseInt(firstDayEl.style.width, 10);
        if (nativeDayWidth > 0 && nativeDayWidth < 120) { // Compressed
            targetDayWidth = window.innerWidth - 40;
            globalScale = targetDayWidth / nativeDayWidth;
            window.fossnoteScale = globalScale;
            window.fossnoteTargetWidth = targetDayWidth;
        } else if (nativeDayWidth >= 120) {
            targetDayWidth = nativeDayWidth;
            globalScale = 1;
            window.fossnoteScale = 1;
            window.fossnoteTargetWidth = targetDayWidth;
        }
    }

    if (globalScale > 1) {
        // 1. Scale headers
        document.querySelectorAll('[id*="_titreTranche"]:not([data-scaled])').forEach(el => {
            el.style.width = targetDayWidth + 'px';
            if (el.firstElementChild) el.firstElementChild.style.width = targetDayWidth + 'px';
            el.dataset.scaled = "true";
        });

        // 2. Map courses X and Width
        document.querySelectorAll('.EmploiDuTemps_Element:not([data-scaled])').forEach(el => {
            const left = parseFloat(el.style.left);
            const width = parseFloat(el.style.width);
            if (!isNaN(left) && !isNaN(width)) {
                el.style.left = (left * globalScale) + 'px';
                el.style.width = (width * globalScale) + 'px';
            }
            el.dataset.scaled = "true";
        });

        // 3. Stretch canvases and map their left offsets
        document.querySelectorAll('canvas:not([data-scaled])').forEach(canvas => {
            const nativeW = parseInt(canvas.getAttribute('width'), 10);
            const nativeLeft = parseFloat(canvas.style.left);
            
            if (nativeW > 0) {
                canvas.style.width = (nativeW * globalScale) + 'px';
            }
            if (!isNaN(nativeLeft)) {
                canvas.style.left = (nativeLeft * globalScale) + 'px';
            }
            canvas.dataset.scaled = "true";
        });

        // 4. Update containers and overlays
        const totalDays = document.querySelectorAll('[id*="_titreTranche"]').length || 6;
        const totalWidth = targetDayWidth * totalDays;
        
        headerViewport.style.setProperty('width', totalWidth + 'px', 'important');
        gridViewport.style.setProperty('width', totalWidth + 'px', 'important');

        const grilleOverlay = document.querySelector('[id$="_Grille_"]');
        if (grilleOverlay) {
            grilleOverlay.style.setProperty('width', totalWidth + 'px', 'important');
        }
    }

    // Always clip to exactly one day width
    headerViewport.style.setProperty('clip-path', `inset(0 calc(100% - ${targetDayWidth}px) 0 0)`, 'important');
    gridViewport.style.setProperty('clip-path', `inset(0 calc(100% - ${targetDayWidth}px) 0 0)`, 'important');

    const dayWidth = targetDayWidth;

    // Prevent Pronote's native horizontal scroll from revealing other days
    const preventScroll = (e) => { if (e.target.scrollLeft > 0) e.target.scrollLeft = 0; };
    if (!gridViewport.dataset.scrollLocked) {
        gridViewport.dataset.scrollLocked = "true";
        gridViewport.addEventListener('scroll', preventScroll, { passive: true });
        headerViewport.addEventListener('scroll', preventScroll, { passive: true });
    }

    // Prevent inserting duplicate navbars
    let navBar = document.querySelector(".fossnote-day-nav");
    if (!navBar) {
        navBar = document.createElement("div");
        navBar.className = "fossnote-day-nav";
        navBar.innerHTML = `
            <button id="fn-prev-day" type="button">&larr; Précédent</button>
            <span id="fn-day-title">Lundi</span>
            <button id="fn-next-day" type="button">Suivant &rarr;</button>
        `;
        // Insert directly before the main grid container
        grille.parentNode.insertBefore(navBar, grille);
    }

    const prevBtn = navBar.querySelector("#fn-prev-day");
    const nextBtn = navBar.querySelector("#fn-next-day");
    const dayTitle = navBar.querySelector("#fn-day-title");

    function renderView() {
        const offset = -(currentDayIndex * dayWidth);

        // Slide both header and grid content simultaneously using CSS transform
        headerContent.style.transform = `translateX(${offset}px)`;
        gridContent.style.transform = `translateX(${offset}px)`;

        // Sync day label with the native header text
        const titleEl = document.querySelector(`[id$="_titreTranche${currentDayIndex}"] div`);
        if (titleEl && titleEl.textContent.trim()) {
            const newTitle = titleEl.textContent.trim();
            if (dayTitle.textContent !== newTitle) {
                dayTitle.textContent = newTitle;
            }
        }

        prevBtn.disabled = currentDayIndex <= 0;
        nextBtn.disabled = currentDayIndex >= totalDays - 1;
    }

    if (!navBar.dataset.bound) {
        navBar.dataset.bound = "true";

        prevBtn.addEventListener("click", () => {
            if (currentDayIndex > 0) {
                currentDayIndex--;
                renderView();
            }
        });

        nextBtn.addEventListener("click", () => {
            if (currentDayIndex < totalDays - 1) {
                currentDayIndex++;
                renderView();
            }
        });
    }

    // --- Touch Swipe Gestures ---
    if (!grille.dataset.swipeBound) {
        grille.dataset.swipeBound = "true";
        let touchStartX = 0;
        let touchEndX = 0;

        grille.addEventListener('touchstart', e => {
            touchStartX = e.changedTouches[0].screenX;
        }, { passive: true });

        grille.addEventListener('touchend', e => {
            touchEndX = e.changedTouches[0].screenX;
            handleSwipe();
        }, { passive: true });

        function handleSwipe() {
            const threshold = 50; // Minimum distance to trigger swipe
            if (touchStartX - touchEndX > threshold) {
                // Swipe Left -> Next Day
                if (currentDayIndex < totalDays - 1) {
                    currentDayIndex++;
                    renderView();
                }
            } else if (touchEndX - touchStartX > threshold) {
                // Swipe Right -> Previous Day
                if (currentDayIndex > 0) {
                    currentDayIndex--;
                    renderView();
                }
            }
        }
    }

    renderView();
}

/**
 * Normalizes input text to automatically insert a space after "BUT" (e.g. "BUT3" -> "BUT 3").
 */
function setupPromoInputFix() {
    const input = document.querySelector('[id="IE.Identite.collection._3.Instances[1].Instances[1].bouton_Edit"]');
    if (!input || input.dataset.fossnoteBound) return;

    input.dataset.fossnoteBound = "true";

    input.addEventListener("input", (e) => {
        const val = e.target.value;
        const formatted = val.replace(/\b(but)(\d)\b/gi, "$1 $2").toUpperCase();

        if (formatted !== val) {
            e.target.value = formatted;
            e.target.dispatchEvent(new Event("input", { bubbles: true }));
        }
    });
}

// Continuous observer for dynamic client-side rendering
const logoSelector = '[id="IE.Identite.collection._3.Instances[0].Instances[0]"] header div.ibe_droite a';

const observer = new MutationObserver(() => {
    const logo = document.querySelector(logoSelector);
    if (logo && logo.href !== "https://github.com/xFufly/fossnote") {
        update(logo);
    }

    setupPromoInputFix();
    initDayNavigator();
});

observer.observe(document.documentElement, {
    childList: true,
    subtree: true
});